flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: 93d0593a9e72c6379231c65984a0698efadabbb0
- location:
    git: https://github.com/cauterize-tools/crucible.git
    commit: v1.0.0
extra-deps:
  - gitrev-1.2.0
  - s-cargot-0.1.0.0
resolver: lts-7.18
