flags: {}
packages:
- '.'
- location:
    git: https://github.com/cauterize-tools/cauterize.git
    commit: 8e93b4dbdf85e6ed47e520a3bdc75ea9f0940d07
extra-deps:
 - s-cargot-0.1.0.0
resolver: lts-2.21
